apiVersion: apps/v1
kind: Deployment
metadata:
    name: myhtmlweb-deploy1
spec: 
    replicas: 1
    selector:
         matchLabels:
             env: production
    template:
         metadata:
              name: myhtmlweb-pod
              labels:   
                  env: production
                  region: IN
         spec:
              containers:
              -   name: myhtmlweb-con 
                  image: nishant70/phpimage:v1
                  volumeMounts:
                  -    mountPath: "/var/log/jenkins"
                       name: jenkins-pvc
              volumes:
              -   name: jenkins-pvc
                  persistentVolumeClaim:
                       claimName: pv-claim-jenkins
