apiVersion: apps/v1
kind: Deployment
metadata:
    name: myphpweb-deploy
spec: 
    replicas: 1
    selector:
         matchLabels:
             env: production
    template:
         metadata:
              name: myphpweb-pod
              labels:   
                  env: production
                  region: IN
         spec:
              containers:
              -   name: myphpweb-con 
                  image: vimal13/apache-webserver-php
                  ports:
                  -    containerPort: 80
                  volumeMounts:
                  -    mountPath: "/usr/local/apache2/htdocs"
                       name: jenkins-pvc
              volumes:
              -   name: jenkins-pvc
                  persistentVolumeClaim:
                       claimName: pv-claim-jenkins
