apiVersion: apps/v1
kind: Deployment
metadata:
    name: myphpweb-deploy
    labels: 
         app: webapp
spec: 
    selector:
         matchLabels:
             app: webapp
             env: production
    template:
         metadata:
              name: myphpweb-pod
              labels:   
                  env: production
                  app: webapp
         spec:
              containers:
              -   name: myphpweb-con 
                  image: nishant70/phpimage:v1
                  ports:
                  -    containerPort: 80
                  volumeMounts:
                  -    mountPath: "/usr/local/apache2/htdocs"
                       name: jenkins-pvc
              volumes:
              -   name: jenkins-pvc
                  persistentVolumeClaim:
                       claimName: pv-claim-jenkins
