apiVersion: apps/v1
kind: Deployment
metadata:
    name: myphpweb-deploy
spec: 
    replicas: 2
    selector:
         matchLabels:
             env: production
    template:
         metadata:
              name: myphpweb-pod
              labels:   
                  env: production
                  region: IN
         spec:
              containers:
              -   name: myphpweb-con 
                  image: nishant70/phpimage:v1
         volumes:
         
